version: "3.9"

networks:
  internal:
    driver: bridge

volumes:
  prometheus_data: 
  grafana_data:

services:
  fiber-stats:
    build: .
    container_name: fiber-stats
    restart: unless-stopped
    networks:
      - internal

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - internal
    depends_on:
      - fiber-stats
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - internal
    ports:
      - 80:3000
    depends_on:
      - prometheus