version: "3.9"

networks:
  internal:
    driver: bridge

volumes:
  prometheus_data: 

services:
  fiber-stats:
    build: .
    container_name: fiber-stats
    restart: unless-stopped
    networks:
      - internal

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - internal
    ports:
      - 9090:9090